services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"      

  libs:
    build: 
      dockerfile: Dockerfile.libs
    container_name: libs
    env_file:
      - .env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy      