"""add unique in motivation models

Revision ID: 0bcfd412daed
Revises: 665ce4f7673c
Create Date: 2025-01-30 10:42:44.577060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bcfd412daed'
down_revision: Union[str, None] = '665ce4f7673c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('date', sa.Date(), nullable=False))
    op.alter_column('meetings', 'time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_motivations_task_id'), 'motivations', ['task_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_motivations_task_id'), 'motivations', type_='unique')
    op.alter_column('meetings', 'time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('meetings', 'date')
    # ### end Alembic commands ###
