"""added constr for taskuser

Revision ID: d367e9cca016
Revises: 56f0ab2b20d8
Create Date: 2025-01-30 02:30:45.394723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd367e9cca016'
down_revision: Union[str, None] = '56f0ab2b20d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_taskuser_task_id'), 'taskuser', ['task_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_taskuser_task_id'), 'taskuser', type_='unique')
    # ### end Alembic commands ###
