"""fix time field

Revision ID: fd9638501a4b
Revises: e7e31e62d9e0
Create Date: 2025-02-02 21:44:51.251964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd9638501a4b'
down_revision: Union[str, None] = 'e7e31e62d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
