"""fix news model

Revision ID: 903ae1895566
Revises: 96700e2990bf
Create Date: 2025-01-29 05:42:41.137715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903ae1895566'
down_revision: Union[str, None] = '96700e2990bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_companies_news_id_news', 'companies', type_='foreignkey')
    op.drop_column('companies', 'news_id')
    op.add_column('news', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_news_company_id_companies'), 'news', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_news_company_id_companies'), 'news', type_='foreignkey')
    op.drop_column('news', 'company_id')
    op.add_column('companies', sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_companies_news_id_news', 'companies', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
