"""add unique in meeting models

Revision ID: d22425cc37f1
Revises: 0bcfd412daed
Create Date: 2025-01-30 14:11:17.031436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22425cc37f1'
down_revision: Union[str, None] = '0bcfd412daed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_meeting_user_meeting_id'), 'meeting_user', ['meeting_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_meeting_user_meeting_id'), 'meeting_user', type_='unique')
    # ### end Alembic commands ###
