"""add unique fk

Revision ID: 0b23f1af2eb4
Revises: 903ae1895566
Create Date: 2025-01-29 16:57:57.280646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b23f1af2eb4'
down_revision: Union[str, None] = '903ae1895566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_organization_company_id'), 'organization', ['company_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_organization_company_id'), 'organization', type_='unique')
    # ### end Alembic commands ###
