"""dix field name

Revision ID: d12aa0973153
Revises: da5cf7e61eee
Create Date: 2025-01-29 04:17:38.751172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12aa0973153'
down_revision: Union[str, None] = 'da5cf7e61eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('company_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_organization_compamy_id_companies', 'organization', type_='foreignkey')
    op.create_foreign_key(op.f('fk_organization_company_id_companies'), 'organization', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('organization', 'compamy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('compamy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_organization_company_id_companies'), 'organization', type_='foreignkey')
    op.create_foreign_key('fk_organization_compamy_id_companies', 'organization', 'companies', ['compamy_id'], ['id'], ondelete='CASCADE')
    op.drop_column('organization', 'company_id')
    # ### end Alembic commands ###
